Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,20 +13,20 @@ jobs:
   - name: Install Go
     uses: actions/setup-go@v6.0.0
     with: 
-      go-version: 1.23
+      go-version-file: 'go.mod'
   - name: Run Gosec Security Scanner
     uses: securego/gosec@v2.21.4
     with: 
-     args: ./... 
+     args: './... -fmt sarif -out results.sarif'
   - name: Check for SARIF File
-    run: ls -la results.json || echo "results.json not found"
+    run: ls -la results.sarif || echo "results.sarif not found"
     if: always()
   - name: Upload Report
     uses: actions/upload-artifact@v4.6.2
     if: always()
     with:
      name: gosec report
-     path: results.json
+     path: results.sarif
 
       
     
