Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,16 +17,16 @@ jobs:
   - name: Run Gosec Security Scanner
     uses: securego/gosec@v2.21.4
     with: 
-     args: ' -severity high -fmt sarif -out results.sarif  ./... '
+     args: './... -fmt json -out results.json -severity medium'
   - name: Check for SARIF File
-    run: ls -la results.sarif || echo "results.sarif not found"
+    run: ls -la results.json || echo "results.json not found"
     if: always()
   - name: Upload Report
     uses: actions/upload-artifact@v4.6.2
     if: always()
     with:
      name: gosec report
-     path: results.sarif
+     path: results.json
 
       
     
